name: Test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest # 运行环境

    steps:
      - name: Cache cache folder
        uses: actions/cache@v2
        with:
          path: cache
          key: ${{ runner.os }}-cache-${{ hashFiles('./cache/text.txt') }}


      - uses: actions/checkout@v4 # 拉取代码
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
           ls
           python main.py
